#ifndef _H_EMULATOR_DEFINITIONS
#define _H_EMULATOR_DEFINITIONS

#define DEBUG_MODE true

#define MEMORY_SIZE 65536
#define REGISTER_SIZE 8
#define CARTRIDGE_MAX_SIZE 524288

#define GRAPHIC_WIDTH 256
#define GRAPHIC_HEIGHT 240
#define GRAPHIC_VRAM_SIZE 16384
#define GRAPHIC_REGISTER_SIZE 16

#endif
