#ifndef _H_EMULATOR_DEFINITIONS
#define _H_EMULATOR_DEFINITIONS

#define DEBUG_MODE true

#define MEMORY_SIZE 65536 // RAM
#define REGISTER_SIZE 8
#define CARTRIDGE_MAX_SIZE 524288

#define GRAPHIC_WIDTH 256
#define GRAPHIC_HEIGHT 192

#endif
